<a href="https://colab.research.google.com/github/bitprj/DigitalHistory/blob/Atul/Week8-Intro-to-Statistical-Analysis-and-Methods/Week_8_Homework_SOLUTIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <div align = "center">Homework 8</div>
# <div align = "center">NumPy</div>

Welcome to Homework 8. In this homework you will be using techniques you learned throughout Week 8. The purpose of this homework is to get you more familiar with using NumPy and master manipulating arrays. Feel free to refer to the cheatsheet while working through these problems.

## Import Libraries

In [ ]:
import numpy as np

## Grading 

Every question in this homework is worth 2 points. There are a total of 10 questions.

## NumPy Questions

### Q1: Generate a 4x4 matrix with values ranging from 5 to 20.

In [ ]:
x =  np.arange(5, 21).reshape(4,4)
print(x)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


### Create Array


In [ ]:
# Create Array
np.random.seed(24) # This guarantees the code will generate the same set of random numbers whenever executed
arr = np.random.randint(1,high=600000, size=(10, 5))
arr

array([[242083,    900, 211137, 516440, 478610],
       [452754, 414850, 268645, 407557, 307184],
       [506084, 298876, 300516, 190227, 552612],
       [524000, 303489, 518669, 538685, 341048],
       [429383, 588642,  26247, 306479, 448322],
       [284592, 407770, 270923, 498939,  53532],
       [184866, 519428, 582533, 261954, 197631],
       [238905, 119560, 388230, 396733, 355499],
       [ 55417, 489583,  39574, 245868, 291493],
       [180014, 142945,  33273, 355671, 510243]])

### Q2: Obtain the average value of the third column

In [ ]:
np.mean(arr[:,2])

263974.7

### Q3: Obtain the average value of the first 6 rows of the fourth and fifth columns?

In [ ]:
np.mean(arr[0:6,3:4])

409721.1666666667

### Q4: Create a 2x3 matrix of numbers from 1-6, then a 1D array of numbers from 1-3. Add them and display the result

In [ ]:
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])

second_matrix = np.array([1, 2, 3])

first_matrix + second_matrix

[[1 2 3]
 [4 5 6]]
[1 2 3]


array([[2, 4, 6],
       [5, 7, 9]])

### Q5: Create an array with numbers from 1 to 10. Filter out all the multiples of 4 and display the result.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
filter = my_vector % 4 == 0
arr[filter]

array([4, 8])

### Q6: Create an array with numbers from 1-4. Change the value of the first index to 0 without directly modifying the array.

In [ ]:
arr = np.array([1, 2, 3, 4])
new_arr = arr
arr[0] = 0
arr

array([0, 2, 3, 4])

### Q7: Create a 2x3 matrix with values from 1-6. Obtain all rows from the second and third columns.

In [ ]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
my_slice = my_array[:, 1:3]
my_slice

array([[2, 3],
       [5, 6]])

### Q8: Create an array with numbers 1-10. In one line, zero out all multiples of 3.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10])
arr[arr%3 == 0] = 0
arr

array([ 0,  1,  2,  0,  4,  5,  0,  7,  8,  0, 10])

### Q9: Do the above but without modifying the original array.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10])
new_arr = arr.copy()
new_arr[new_arr%3 == 0] = 0
print(arr)
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  0  4  5  0  7  8  0 10]


### Q10: Create a 5x5 array of all 1's. Then, in one line, modify the array so that it has 1's along the border but 0's everywhere else.

EXPECTED OUTPUT:

[[1. 1. 1. 1. 1.]

 [1. 0. 0. 0. 1.]

 [1. 0. 0. 0. 1.]

 [1. 0. 0. 0. 1.]
 
 [1. 1. 1. 1. 1.]]

In [ ]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
