# SECTIONS

## Creating Arrays

## Indexing

## Slicing

## Data Types

## Copy, View

## Shape (Not whole section, but mini?)

## Reshaping Arrays

## Iterating Arrays

## Join, Split

## Search, Sort, Filter

## Random (Any distributions?)

## Universal Functions
  1. Vectorization
  2.This is where we talk about cumsum()

# Creating Arrays *

NumPy allows you to work with arrays very efficiently. The array object in NumPy is called *ndarray*.

We can create a NumPy ndarray object by using the array() function.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10])

print(arr)

print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


**Different dimensions of arrays?**

# Indexing

Indexing is the same thing as accessing an element of a list. In this case, we will be accessing an array element.

You can access an array element by referring to its **index number**. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

The following example shows how you can access multiple elements of an array and perform operations on them.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4,5,6,7,8,9,10])

print(arr[4] + arr[8])

14


# Slicing

Slicing in python means taking a part or subsection of an object. An array in this case.

We slice using this syntax: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass a start it's considered that we start from the beginning. If we don't pass an end its considered that we slice to the end of the array.

If we don't pass step, we slice one element at a time. Additionally, we don't aloways have to step through an array from beginning to end. We can also go backwards. For instance:

In [2]:
# Reverse an array through backwards/negative stepping
import numpy as np
arr = np.array([3,7,9,0])

print(arr[::-1])

[0 9 7 3]


In [ ]:
# Slice elements from the beginning to index 8

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

print(arr[:8])

[1 2 3 4 5 6 7 8]


You'll notice we only got to index 7. That's because the end is always *non-inclusive*. We slice up to but not including the end value. The start index on the other hand, **is** inclusive.

# Data Types

Just like base Python, NumPy has many data types available. They are all differentiated by a single character. Below is a list of all data types:

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [ ]:
# Checking the data type of an array
import numpy as np

arr = np.array([5, 7, 3, 1])

print(arr.dtype)

int64


In [ ]:
# How to create an array with a defined type
import numpy as np

arr = np.array([5, 7, 3, 1], dtype='S')

print(arr)
print(arr.dtype)

[b'5' b'7' b'3' b'1']
|S1


In [ ]:
# How to convert between types
import numpy as np

arr = np.array([4.4, 24.1, 25.1,3.5])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[ 4 24 25  3]
int32


# Copy vs. View

In NumPy, you can work with either a copy of the data or the data itself, and it's very important that you know the difference. Namely, modifying a copy of the data will not change the original dataset but modifying the view **will**. Here are some examples:

In [ ]:
# A Copy
import numpy as np

arr = np.array([6, 2, 1, 5, 3])
x = arr.copy()
arr[0] = 8

print(arr)
print(x)

[8 2 1 5 3]
[6 2 1 5 3]


In [ ]:
# A View
import numpy as np

arr = np.array([6, 2, 1, 5, 3])
x = arr.view()
arr[0] = 8

print(arr)
print(x)

[8 2 1 5 3]
[8 2 1 5 3]


# Shape

All NumPy arrays have an attribute called *shape*. This is helpful for 2d or n-dimensional arrays, but for simple lists, it is simply the number of elements that it has.

In [ ]:
# Print the shape of an array
import numpy as np

arr = np.array([2,7,3,7])

print(arr.shape)

(4,)


# Reshaping Arrays *

# Iterating Through Arrays *

Iterating simply means to traverse or travel through an object. In the case of arrays, we can iterate through them by using simple for loops.

In [ ]:
import numpy as np

arr = np.array([1, 5, 7])

for x in arr:
  print(x)

1
5
7


# Joining Arrays *

Joining combining the elements of multiple arrays into one.

The basic way to do it is like this:

In [ ]:
import numpy as np

arr1 = np.array([7, 1, 0])

arr2 = np.array([2, 8, 1])

arr = np.concatenate((arr1, arr2))

print(arr)

[7 1 0 2 8 1]


## Stack Functions

# Splitting Arrays

Splitting is the opposite of joining arrays. It takes one array and creates multiple from it.

In [ ]:
# Split array into 4
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6,7,8])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


# Searching Arrays *

Searching an array to find a certain element is a very important and basic operation. We can do this using the *where()* method.

In [ ]:
import numpy as np

arr = np.array([1, 2, 5, 9, 5, 3, 4])

x = np.where(arr == 4)

print(x)

(array([6]),)


In [ ]:
# Find all the odd numbers in an array
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80,99])

x = np.where(arr%2 == 1)

print(x)

(array([8]),)


# Sorting Arrays

Sorting an array is another very important and commonly used operation. NumPy has a function called sort() for this task.

In [ ]:
import numpy as np

arr = np.array([4, 1, 0, 3])

print(np.sort(arr))

[0 1 3 4]


In [ ]:
# Sorting a string array alphabetically
import numpy as np

arr = np.array(['zephyr', 'gate', 'match'])

print(np.sort(arr))

['gate' 'match' 'zephyr']


# Filtering Arrays

Sometimes you would want to create a new array from an existing array where you select elements out based on a certain condition. Let's say you have an array with all integers from 1 to 10. You would like to create a new array with only the odd numbers from that list. You can do this very efficiently with **filtering**. When you filter something, you only take out what you want, and the same principle applies to objects in NumPy. NumPy uses what's called a **boolean index list** to filter. This is an array of True and False values that correspond directly to the target array and what values you would like to filter. For example, using the example above, the target array would look like this:

[1,2,3,4,5,6,7,8,9,10]

And if you wanted to filter out the odd values, you would use this particular boolean index list:

[True,False,True,False,True,False,True,False,True,False]

Applying this list onto the target array will get you what you want:

[1,3,5,7,9]

A working code example is shown below:

In [ ]:
import numpy as np

arr = np.array([51, 52, 53, 54])

x = [False, False, True, True]

newarr = arr[x]

print(newarr)

[53 54]


We don't need to hard-code the True and False values. Like stated previously, we can filter based on conditions.

In [ ]:
arr = np.array([51, 52, 53, 54])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 52, set the value to True, otherwise False:
  if element > 52:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[53 54]


Filtering is a very common task when working with data and as such, NumPy has an even more efficient way to perform it. It is possible to create a boolean index list directly from the target array and then apply it to obtain the filtered array. See the example below:

In [4]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80,90,100])

filter = arr > 50

filter_arr = arr[filter]

print(filter)
print(filter_arr)

[False False False False False  True  True  True  True  True]
[ 60  70  80  90 100]


# Random Numbers and Distributions *

# Universal Functions *
