<a href="https://colab.research.google.com/github/bitprj/DigitalHistory/blob/Atul/Week7-Intro-to-Statistical-Analysis-and-Methods/Week_7_NTT_Answer_Key.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1.0 Now Try This:

Create an array of at least size 10 and populate it with random numbers. Then, use slicing to split it into two and create two new arrays. Then, find the sum of the third digits in each array.

In [5]:
import numpy as np

arr = np.array([1,3,5,7,9,2,4,6,8,12,45,26,36,21,53,78,21,94])

arr1 = arr[:9]
arr2 = arr[9:]

print(arr1)
print(arr2)

sum = arr1[2] + arr2[2]

print(sum)

[1 3 5 7 9 2 4 6 8]
[12 45 26 36 21 53 78 21 94]
31


### 2.0 Now Try This:

Create an array with the first 10 numbers of the Fibonacci sequence. Split this array into two. On each half, search for any multiples of 4. Next, filter both arrays for multiples of 5. Finally, take the two filtered arrays, join them, and sort them.

In [18]:
import numpy as np

arr = np.array([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

arr1,arr2 = np.array_split(arr,2)

print(arr1)
print(arr2)

x = np.where(arr1 % 4 == 0)
y = np.where(arr2 % 4 == 0)

print(x)
print(y)

filter_1 = (arr1 % 5 == 0)
filter_2 = (arr1 % 5 == 0)

filter_arr1 = arr1[filter_1]
filter_arr2 = arr1[filter_2]

print(filter_arr1)
print(filter_arr2)

new_arr = np.concatenate((filter_arr1,filter_arr2))

print(np.sort(new_arr))

[0 1 1 2 3]
[ 5  8 13 21 34]
(array([0]),)
(array([1]),)
[0]
[0]
[0 0]


### 3.0 Now Try This:

Create a randomly generated array of any size using either the normal or random distributions. Then, calculate the following statistics for that array:

Mean, Median, Variance, Standard Deviation, 84th quantile.

In [25]:
import numpy as np
from numpy import random

arr = random.randint(500,size=(20))

print(arr)

mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
std = np.std(arr)
quan = np.quantile(arr,.84)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std)
print("84th Quantile:", quan)

[498 367 421 331 196 206 144 418 477 257 270 155 118 152  14 243 408 271
  41 158]
Mean: 257.25
Median: 250.0
Variance: 18779.0875
Standard Deviation: 137.0368107480614
84th Quantile: 417.6
