<a href="https://colab.research.google.com/github/bitprj/DigitalHistory/blob/Atul/Week8-Intro-to-Statistical-Analysis-and-Methods/Week_8_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <div align = "center">Homework 8</div>
# <div align = "center">NumPy</div>

Welcome to Homework 8. In this homework you will be using techniques you learned throughout Week 8. The purpose of this homework is to get you more familiar with using NumPy and master manipulating arrays. Feel free to refer to the cheatsheet while working through these problems.

## Import Libraries

In [ ]:
import numpy as np

## Grading 

Every question in this homework is worth 2 points. There are a total of 10 questions.

## NumPy Questions

### Q1: Generate a 4x4 matrix with values ranging from 5 to 20.

In [ ]:
# INSERT CODE HERE

### Create Array


In [ ]:
# Create Array
np.random.seed(24) # This guarantees the code will generate the same set of random numbers whenever executed
arr = np.random.randint(1,high=600000, size=(10, 5))
arr

### Q2: Obtain the average value of the third column

In [ ]:
# INSERT CODE HERE

### Q3: Obtain the average value of the first 6 rows of the fourth and fifth columns

In [ ]:
# INSERT CODE HERE

### Q4: Create a 2x3 matrix of numbers from 1-6, then a 1D array of numbers from 1-3. Add them and display the result

In [ ]:
# INSERT CODE HERE

### Q5: Create an array with numbers from 1 to 10. Filter the array to only include multiples of 4 and display the result.

In [ ]:
# INSERT CODE HERE

### Q6: Create an array with numbers from 1-4. Change the value of the first index to 0 without directly modifying the array.

In [ ]:
# INSERT CODE HERE

### Q7: Create a 2x3 matrix with values from 1-6. Obtain all rows from the second and third columns.

In [ ]:
# INSERT CODE HERE

### Q8: Create an array with numbers 1-10 and then zero out all multiples of 3.

In [ ]:
# INSERT CODE HERE

### Q9: Do the above but without modifying the original array.

In [ ]:
# INSERT CODE HERE

### Q10: Create a 5x5 array of all 1's. Then, modify the array so that it has 1's along the border but 0's everywhere else.

EXPECTED OUTPUT:

[[1. 1. 1. 1. 1.]

 [1. 0. 0. 0. 1.]

 [1. 0. 0. 0. 1.]

 [1. 0. 0. 0. 1.]
 
 [1. 1. 1. 1. 1.]]

In [ ]:
# INSERT CODE HERE